# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Stop service
      run: sudo systemctl stop telegram-bot.service
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish
      run: sudo dotnet publish -c Release -o /var/www/TelegramTimetableBot
    - name: Start service
      run: sudo systemctl start telegram-bot.service
