name: .NET

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Stopping systemd service
      run: sudo systemctl stop telegram-bot.service
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release -o /home/ubuntu/app
    - name: Starting systemd service
      run: sudo systemctl start telegram-bot.service
