name: .NET

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Stop service
      run: sudo systemctl stop telegram-bot.service
    - name: Copy files
      run: cp -r . /home/ubuntu/app
    - name: Start service
      run: sudo systemctl start telegram-bot.service
